import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Rental Mobil Banjarbaru & Sewa Murah ✅ Bandara 24 Jam",
  description: "Rental dan sewa mobil di Banjarbaru dekat Bandara Syamsudin Noor. Harga murah, unit terawat, lepas kunci atau driver ramah.",
};

const rawHtml = `<main class="pt-20"> <!-- Added padding for fixed navbar -->    <section class="bg-gradient-to-br from-gray-900 via-gray-800 to-red-900 text-white py-20"> <div class="container mx-auto px-4 lg:px-8"> <nav class="flex mb-8 text-sm text-gray-300" aria-label="Breadcrumb"> <ol class="flex items-center space-x-2"> <li><a href="/" class="hover:text-yellow-400">Beranda</a></li> <li><span class="mx-2">/</span></li> <li class="text-yellow-400 font-medium">Sewa Mobil Banjarbaru</li> </ol> </nav> <div class="grid lg:grid-cols-2 gap-12 items-center"> <div> <span class="inline-block px-4 py-2 bg-yellow-400 text-gray-900 font-bold text-sm rounded-full mb-6">
🚗 RENTAL MOBIL BANJARBARU
</span> <h1 class="text-4xl md:text-5xl lg:text-6xl font-black leading-tight mb-6">
Rental & Sewa Mobil <span class="text-yellow-400">Banjarbaru</span> </h1> <p class="text-lg text-gray-300 mb-8 leading-relaxed">
Butuh <strong>rental mobil murah di Banjarbaru</strong>? Deaz Rental Mobil Banjarmasin hadir melayani kebutuhan transportasi Anda di wilayah Banjarbaru, <strong>Martapura</strong>, sekitar <strong>Bandara Syamsudin Noor</strong>, hingga ke Loksado. Armada terawat, lepas kunci atau dengan supir!
</p> <div class="flex flex-wrap gap-4 mb-8"> <a href="https://wa.me/6281255964566?text=Halo+Deaz+Rental+Saya+di+Banjarbaru+ingin+sewa+mobil" class="px-8 py-4 bg-yellow-400 text-gray-900 font-bold rounded-lg hover:bg-yellow-300 transition-all shadow-lg inline-flex items-center gap-2"> <i data-lucide="message-circle" class="w-5 h-5"></i>
Chat WhatsApp
</a> <a href="/#armada" class="px-8 py-4 bg-transparent border-2 border-white text-white font-bold rounded-lg hover:bg-white/10 transition-all">
Lihat Semua Armada
</a> </div> <!-- Trust Badges --> <div class="flex flex-wrap gap-6 text-sm"> <div class="flex items-center gap-2"> <i data-lucide="shield-check" class="w-5 h-5 text-green-400"></i> <span>Asuransi Tersedia</span> </div> <div class="flex items-center gap-2"> <i data-lucide="clock" class="w-5 h-5 text-green-400"></i> <span>Layanan 24 Jam</span> </div> <div class="flex items-center gap-2"> <i data-lucide="map-pin" class="w-5 h-5 text-green-400"></i> <span>Delivery Banjarbaru</span> </div> </div> </div> <div class="relative hidden lg:block"> <div class="absolute -inset-4 bg-gradient-to-r from-yellow-400 to-red-600 rounded-2xl blur-lg opacity-30"></div> <img src="/images/hero-image_Zs3daf.webp" alt="Sewa Mobil Banjarbaru - Deaz Rental" title="Rental Mobil Banjarbaru Terpercaya" loading="lazy" decoding="async" fetchpriority="auto" width="600" height="400" class="relative rounded-2xl shadow-2xl"> </div> </div> </div> </section>  <section class="py-16 bg-white"> <div class="container mx-auto px-4"> <h2 class="text-3xl md:text-4xl font-bold text-center mb-4">
Mengapa Pilih <span class="text-red-800">Deaz Rental</span> di Banjarbaru?
</h2> <p class="text-gray-600 text-center mb-12 max-w-2xl mx-auto">
Kami memahami kebutuhan transportasi masyarakat Banjarbaru dan sekitarnya
</p> <div class="grid md:grid-cols-2 lg:grid-cols-4 gap-8"> <div class="text-center p-6 rounded-xl bg-gray-50 hover:bg-red-50 transition-colors"> <div class="w-16 h-16 bg-red-100 rounded-full flex items-center justify-center mx-auto mb-4"> <i data-lucide="truck" class="w-8 h-8 text-red-800"></i> </div> <h3 class="font-bold text-lg mb-2">Delivery ke Banjarbaru</h3> <p class="text-gray-600 text-sm">Kami antar mobil langsung ke lokasi Anda di Banjarbaru, Martapura, atau Bandara</p> </div> <div class="text-center p-6 rounded-xl bg-gray-50 hover:bg-red-50 transition-colors"> <div class="w-16 h-16 bg-red-100 rounded-full flex items-center justify-center mx-auto mb-4"> <i data-lucide="banknote" class="w-8 h-8 text-red-800"></i> </div> <h3 class="font-bold text-lg mb-2">Harga Lokal Bersaing</h3> <p class="text-gray-600 text-sm">Harga sewa mulai Rp 300.000/hari tanpa biaya tersembunyi</p> </div> <div class="text-center p-6 rounded-xl bg-gray-50 hover:bg-red-50 transition-colors"> <div class="w-16 h-16 bg-red-100 rounded-full flex items-center justify-center mx-auto mb-4"> <i data-lucide="car" class="w-8 h-8 text-red-800"></i> </div> <h3 class="font-bold text-lg mb-2">Armada Terupdate</h3> <p class="text-gray-600 text-sm">Unit tahun muda, AC dingin, interior bersih dan wangi</p> </div> <div class="text-center p-6 rounded-xl bg-gray-50 hover:bg-red-50 transition-colors"> <div class="w-16 h-16 bg-red-100 rounded-full flex items-center justify-center mx-auto mb-4"> <i data-lucide="users" class="w-8 h-8 text-red-800"></i> </div> <h3 class="font-bold text-lg mb-2">Driver Berpengalaman</h3> <p class="text-gray-600 text-sm">Driver hafal rute Banjarbaru, Martapura, wisata Kalsel</p> </div> </div> </div> </section>  <section class="py-16 bg-gray-900 text-white"> <div class="container mx-auto px-4"> <h2 class="text-3xl md:text-4xl font-bold text-center mb-4">
Area Layanan di <span class="text-yellow-400">Banjarbaru</span> & Sekitarnya
</h2> <p class="text-gray-400 text-center mb-12 max-w-2xl mx-auto">
Kami melayani penjemputan dan pengantaran ke berbagai lokasi strategis
</p> <div class="grid md:grid-cols-3 gap-6 max-w-4xl mx-auto"> <div class="bg-gray-800 p-6 rounded-xl"> <h3 class="font-bold text-yellow-400 mb-4 flex items-center gap-2"> <i data-lucide="map-pin" class="w-5 h-5"></i> Kota Banjarbaru
</h3> <ul class="space-y-2 text-gray-300 text-sm"> <li>• Landasan Ulin</li> <li>• Banjarbaru Utara</li> <li>• Banjarbaru Selatan</li> <li>• Cempaka</li> <li>• Liang Anggang</li> </ul> </div> <div class="bg-gray-800 p-6 rounded-xl"> <h3 class="font-bold text-yellow-400 mb-4 flex items-center gap-2"> <i data-lucide="plane" class="w-5 h-5"></i> Bandara & Sekitar
</h3> <ul class="space-y-2 text-gray-300 text-sm"> <li>• Bandara Syamsudin Noor</li> <li>• Hotel sekitar Bandara</li> <li>• Kawasan Industri</li> <li>• Terminal Km.6</li> <li>• Simpang Empat</li> </ul> </div> <div class="bg-gray-800 p-6 rounded-xl"> <h3 class="font-bold text-yellow-400 mb-4 flex items-center gap-2"> <i data-lucide="mountain" class="w-5 h-5"></i> Wisata Populer
</h3> <ul class="space-y-2 text-gray-300 text-sm"> <li>• Martapura (Pasar Intan)</li> <li>• Loksado (Bamboo Rafting)</li> <li>• Pagat (Pemandian Air Panas)</li> <li>• Masjid Sabilal Muhtadin</li> <li>• Pulau Kembang</li> </ul> </div> </div> </div> </section>  <section class="py-16 bg-white"> <div class="container mx-auto px-4"> <h2 class="text-3xl md:text-4xl font-bold text-center mb-4">
Armada Populer untuk <span class="text-red-800">Banjarbaru</span> </h2> <p class="text-gray-600 text-center mb-12 max-w-2xl mx-auto">
Pilihan unit terbaik untuk perjalanan di Banjarbaru dan sekitarnya
</p> <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4"> <article class="overflow-hidden flex flex-col bg-red-700 rounded-md shadow-lg hover:shadow-xl transition-shadow group"> <div class="flex flex-col flex-1"> <figure class="relative aspect-[4/3] bg-gray-200 overflow-hidden animate-shimmer"> <img src="/images/Toyota_Alphard_Z9sSio.webp" alt="Rental Toyota Alphard Banjarmasin - Deaz Rental Mobil Banjarmasin" title="Sewa Toyota Alphard Banjarmasin Banjarbaru" loading="lazy" decoding="async" fetchpriority="auto" width="400" height="300" class="w-full h-full object-cover object-center transition-transform group-hover:scale-105"> <!-- Gradient Overlay - reduced height to protect branding --> <div class="absolute inset-x-0 bottom-0 h-1/3 bg-gradient-to-t from-red-700 to-transparent"></div> </figure> <div class="p-3 text-white"> <h3 class="text-sm sm:text-base font-bold text-center leading-tight"> Toyota Alphard </h3> </div> </div> <a href="https://api.whatsapp.com/send/?phone=6281255964566&text=Pak%20Saya%20Mau%20Sewa%20Mobil%20*Toyota%20Alphard*%20by%20Deaz%20Rental%20Mobil%20Banjarmasin&type=phone_number&app_absent=0" target="_blank" rel="noopener noreferrer" class="py-4 font-bold text-center text-yellow-300 bg-red-900 rounded-b-md hover:bg-red-950 transition-colors z-10 relative">
Pesan disini
</a> </article><article class="overflow-hidden flex flex-col bg-red-700 rounded-md shadow-lg hover:shadow-xl transition-shadow group"> <div class="flex flex-col flex-1"> <figure class="relative aspect-[4/3] bg-gray-200 overflow-hidden animate-shimmer"> <img src="/images/Toyota_Fortuner_GR_Sport_2fN98a.webp" alt="Rental Toyota Fortuner GR Sport Banjarmasin - Deaz Rental Mobil Banjarmasin" title="Sewa Toyota Fortuner GR Sport Banjarmasin Banjarbaru" loading="lazy" decoding="async" fetchpriority="auto" width="400" height="300" class="w-full h-full object-cover object-center transition-transform group-hover:scale-105"> <!-- Gradient Overlay - reduced height to protect branding --> <div class="absolute inset-x-0 bottom-0 h-1/3 bg-gradient-to-t from-red-700 to-transparent"></div> </figure> <div class="p-3 text-white"> <h3 class="text-sm sm:text-base font-bold text-center leading-tight"> Toyota Fortuner GR Sport </h3> </div> </div> <a href="https://api.whatsapp.com/send/?phone=6281255964566&text=Pak%20Saya%20Mau%20Sewa%20Mobil%20*Toyota%20Fortuner%20GR%20Sport*%20by%20Deaz%20Rental%20Mobil%20Banjarmasin&type=phone_number&app_absent=0" target="_blank" rel="noopener noreferrer" class="py-4 font-bold text-center text-yellow-300 bg-red-900 rounded-b-md hover:bg-red-950 transition-colors z-10 relative">
Pesan disini
</a> </article><article class="overflow-hidden flex flex-col bg-red-700 rounded-md shadow-lg hover:shadow-xl transition-shadow group"> <div class="flex flex-col flex-1"> <figure class="relative aspect-[4/3] bg-gray-200 overflow-hidden animate-shimmer"> <img src="/images/Mitsubishi_Pajero_Sport_Zr6aD.webp" alt="Rental Mitsubishi Pajero Sport Banjarmasin - Deaz Rental Mobil Banjarmasin" title="Sewa Mitsubishi Pajero Sport Banjarmasin Banjarbaru" loading="lazy" decoding="async" fetchpriority="auto" width="400" height="300" class="w-full h-full object-cover object-center transition-transform group-hover:scale-105"> <!-- Gradient Overlay - reduced height to protect branding --> <div class="absolute inset-x-0 bottom-0 h-1/3 bg-gradient-to-t from-red-700 to-transparent"></div> </figure> <div class="p-3 text-white"> <h3 class="text-sm sm:text-base font-bold text-center leading-tight"> Mitsubishi Pajero Sport </h3> </div> </div> <a href="https://api.whatsapp.com/send/?phone=6281255964566&text=Pak%20Saya%20Mau%20Sewa%20Mobil%20*Mitsubishi%20Pajero%20Sport*%20by%20Deaz%20Rental%20Mobil%20Banjarmasin&type=phone_number&app_absent=0" target="_blank" rel="noopener noreferrer" class="py-4 font-bold text-center text-yellow-300 bg-red-900 rounded-b-md hover:bg-red-950 transition-colors z-10 relative">
Pesan disini
</a> </article><article class="overflow-hidden flex flex-col bg-red-700 rounded-md shadow-lg hover:shadow-xl transition-shadow group"> <div class="flex flex-col flex-1"> <figure class="relative aspect-[4/3] bg-gray-200 overflow-hidden animate-shimmer"> <img src="/images/Toyota_Innova_Zenix_Zkm8IB.webp" alt="Rental Toyota Innova Zenix Banjarmasin - Deaz Rental Mobil Banjarmasin" title="Sewa Toyota Innova Zenix Banjarmasin Banjarbaru" loading="lazy" decoding="async" fetchpriority="auto" width="400" height="300" class="w-full h-full object-cover object-center transition-transform group-hover:scale-105"> <!-- Gradient Overlay - reduced height to protect branding --> <div class="absolute inset-x-0 bottom-0 h-1/3 bg-gradient-to-t from-red-700 to-transparent"></div> </figure> <div class="p-3 text-white"> <h3 class="text-sm sm:text-base font-bold text-center leading-tight"> Toyota Innova Zenix </h3> </div> </div> <a href="https://api.whatsapp.com/send/?phone=6281255964566&text=Pak%20Saya%20Mau%20Sewa%20Mobil%20*Toyota%20Innova%20Zenix*%20by%20Deaz%20Rental%20Mobil%20Banjarmasin&type=phone_number&app_absent=0" target="_blank" rel="noopener noreferrer" class="py-4 font-bold text-center text-yellow-300 bg-red-900 rounded-b-md hover:bg-red-950 transition-colors z-10 relative">
Pesan disini
</a> </article><article class="overflow-hidden flex flex-col bg-red-700 rounded-md shadow-lg hover:shadow-xl transition-shadow group"> <div class="flex flex-col flex-1"> <figure class="relative aspect-[4/3] bg-gray-200 overflow-hidden animate-shimmer"> <img src="/images/Toyota_Innova_Reborn_V_ZOFtB7.webp" alt="Rental Toyota Innova Reborn V Banjarmasin - Deaz Rental Mobil Banjarmasin" title="Sewa Toyota Innova Reborn V Banjarmasin Banjarbaru" loading="lazy" decoding="async" fetchpriority="auto" width="400" height="300" class="w-full h-full object-cover object-center transition-transform group-hover:scale-105"> <!-- Gradient Overlay - reduced height to protect branding --> <div class="absolute inset-x-0 bottom-0 h-1/3 bg-gradient-to-t from-red-700 to-transparent"></div> </figure> <div class="p-3 text-white"> <h3 class="text-sm sm:text-base font-bold text-center leading-tight"> Toyota Innova Reborn V </h3> </div> </div> <a href="https://api.whatsapp.com/send/?phone=6281255964566&text=Pak%20Saya%20Mau%20Sewa%20Mobil%20*Toyota%20Innova%20Reborn%20V*%20by%20Deaz%20Rental%20Mobil%20Banjarmasin&type=phone_number&app_absent=0" target="_blank" rel="noopener noreferrer" class="py-4 font-bold text-center text-yellow-300 bg-red-900 rounded-b-md hover:bg-red-950 transition-colors z-10 relative">
Pesan disini
</a> </article><article class="overflow-hidden flex flex-col bg-red-700 rounded-md shadow-lg hover:shadow-xl transition-shadow group"> <div class="flex flex-col flex-1"> <figure class="relative aspect-[4/3] bg-gray-200 overflow-hidden animate-shimmer"> <img src="/images/Toyota_Veloz_Q_1i25kz.webp" alt="Rental Toyota Veloz Q Banjarmasin - Deaz Rental Mobil Banjarmasin" title="Sewa Toyota Veloz Q Banjarmasin Banjarbaru" loading="lazy" decoding="async" fetchpriority="auto" width="400" height="300" class="w-full h-full object-cover object-center transition-transform group-hover:scale-105"> <!-- Gradient Overlay - reduced height to protect branding --> <div class="absolute inset-x-0 bottom-0 h-1/3 bg-gradient-to-t from-red-700 to-transparent"></div> </figure> <div class="p-3 text-white"> <h3 class="text-sm sm:text-base font-bold text-center leading-tight"> Toyota Veloz Q </h3> </div> </div> <a href="https://api.whatsapp.com/send/?phone=6281255964566&text=Pak%20Saya%20Mau%20Sewa%20Mobil%20*Toyota%20Veloz%20Q*%20by%20Deaz%20Rental%20Mobil%20Banjarmasin&type=phone_number&app_absent=0" target="_blank" rel="noopener noreferrer" class="py-4 font-bold text-center text-yellow-300 bg-red-900 rounded-b-md hover:bg-red-950 transition-colors z-10 relative">
Pesan disini
</a> </article> </div> <div class="text-center mt-10"> <a href="/#armada" class="inline-flex items-center gap-2 px-8 py-4 bg-red-800 text-white font-bold rounded-lg hover:bg-red-900 transition-all">
Lihat Semua Armada
<i data-lucide="arrow-right" class="w-5 h-5"></i> </a> </div> </div> </section>  <section class="py-16 bg-gray-50"> <div class="container mx-auto px-4 max-w-3xl"> <h2 class="text-3xl md:text-4xl font-bold text-center mb-12">
FAQ Rental Mobil <span class="text-red-800">Banjarbaru</span> </h2> <div class="space-y-4"> <details class="bg-white rounded-xl shadow-sm p-6 group" open> <summary class="font-bold text-lg cursor-pointer flex justify-between items-center">
Berapa harga sewa mobil di Banjarbaru?
<i data-lucide="chevron-down" class="w-5 h-5 text-gray-400 group-open:rotate-180 transition-transform"></i> </summary> <div class="mt-4 text-gray-600 leading-relaxed"> <p class="mb-4">
Tarif sewa mobil kami di Banjarbaru sangat kompetitif dan fleksibel. Harga bergantung pada tipe armada yang Anda pilih serta durasi pemakaian.
</p> <a href="https://wa.me/6281255964566?text=Halo+Deaz+Rental+Saya+ingin+tanya+harga+sewa+mobil+di+Banjarbaru" class="inline-flex items-center gap-2 text-red-800 font-bold hover:text-red-900 transition-colors"> <i data-lucide="message-circle" class="w-5 h-5"></i>
Klik di sini untuk cek harga & promo area Banjarbaru
</a> </div> </details> <details class="bg-white rounded-xl shadow-sm p-6 group"> <summary class="font-bold text-lg cursor-pointer flex justify-between items-center">
Apakah bisa sewa mobil lepas kunci di Banjarbaru?
<i data-lucide="chevron-down" class="w-5 h-5 text-gray-400 group-open:rotate-180 transition-transform"></i> </summary> <p class="mt-4 text-gray-600 leading-relaxed">
Ya, kami melayani <strong>sewa mobil lepas kunci di Banjarbaru</strong>. Syaratnya: E-KTP asli Kalimantan Selatan, 
            SIM A aktif, Kartu Keluarga, dan siap diverifikasi tim kami. Proses cepat dan mudah!
</p> </details> <details class="bg-white rounded-xl shadow-sm p-6 group"> <summary class="font-bold text-lg cursor-pointer flex justify-between items-center">
Area mana saja yang dilayani dari Banjarbaru?
<i data-lucide="chevron-down" class="w-5 h-5 text-gray-400 group-open:rotate-180 transition-transform"></i> </summary> <p class="mt-4 text-gray-600 leading-relaxed">
Kami melayani seluruh wilayah <strong>Banjarbaru</strong> (Landasan Ulin, Cempaka, Liang Anggang),
<strong>Martapura</strong>, <strong>Bandara Syamsudin Noor</strong>, Banjarmasin, dan destinasi wisata seperti Loksado, Pagat, Pulau Kembang.
</p> </details> <details class="bg-white rounded-xl shadow-sm p-6 group"> <summary class="font-bold text-lg cursor-pointer flex justify-between items-center">
Bisa antar jemput di Bandara Syamsudin Noor?
<i data-lucide="chevron-down" class="w-5 h-5 text-gray-400 group-open:rotate-180 transition-transform"></i> </summary> <p class="mt-4 text-gray-600 leading-relaxed">
Tentu! Kami melayani <strong>antar jemput Bandara Syamsudin Noor</strong> 24 jam. Driver akan standby sesuai jadwal 
            penerbangan Anda. Hubungi kami untuk pemesanan dan info tarif.
</p> </details> </div> <details class="bg-white rounded-xl shadow-sm p-6 group"> <summary class="font-bold text-lg cursor-pointer flex justify-between items-center">
Apakah bisa rental mobil di Martapura?
<i data-lucide="chevron-down" class="w-5 h-5 text-gray-400 group-open:rotate-180 transition-transform"></i> </summary> <p class="mt-4 text-gray-600 leading-relaxed">
Ya! Kami melayani <strong>rental mobil di Martapura</strong> dan sekitarnya. Mobil bisa diantar ke lokasi Anda di Martapura, 
            termasuk area Pasar Intan Cempaka. Jarak Martapura-Banjarbaru hanya ±15 menit, sehingga delivery sangat cepat.
</p> </details> <details class="bg-white rounded-xl shadow-sm p-6 group"> <summary class="font-bold text-lg cursor-pointer flex justify-between items-center">
Apakah ada rental mobil murah di Banjarbaru?
<i data-lucide="chevron-down" class="w-5 h-5 text-gray-400 group-open:rotate-180 transition-transform"></i> </summary> <p class="mt-4 text-gray-600 leading-relaxed">
Deaz Rental menawarkan <strong>harga sewa mobil murah di Banjarbaru</strong> dengan armada berkualitas. 
            Hubungi kami via WhatsApp untuk mendapatkan penawaran terbaik sesuai kebutuhan dan budget Anda.
</p> </details> </div> </section>  <section class="py-20 bg-gradient-to-r from-red-800 to-red-900 text-white text-center"> <div class="container mx-auto px-4"> <h2 class="text-3xl md:text-4xl font-bold mb-6">
Siap Sewa Mobil di Banjarbaru?
</h2> <p class="text-xl opacity-90 mb-10 max-w-2xl mx-auto">
Hubungi kami sekarang untuk ketersediaan unit dan penawaran terbaik. Layanan 24 jam!
</p> <div class="flex flex-wrap justify-center gap-4"> <a href="https://wa.me/6281255964566?text=Halo+Deaz+Rental+Saya+di+Banjarbaru+mau+booking+mobil" class="inline-flex items-center gap-2 px-10 py-5 bg-yellow-400 text-gray-900 font-black text-lg rounded-full hover:bg-yellow-300 transition-all shadow-2xl transform hover:-translate-y-1"> <i data-lucide="message-circle" class="w-6 h-6"></i>
Chat WhatsApp Sekarang
</a> <a href="tel:+6281255964566" class="inline-flex items-center gap-2 px-10 py-5 bg-transparent border-2 border-white text-white font-bold text-lg rounded-full hover:bg-white/10 transition-all"> <i data-lucide="phone" class="w-6 h-6"></i>
Telepon Langsung
</a> </div> </div> </section>  </main>`;

export default function Page() {
  return <div dangerouslySetInnerHTML={{ __html: rawHtml }} />;
}
