import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Metode Pembayaran - Deaz Rental Mobil Banjarmasin",
  description: "Informasi rekening bank resmi dan tata cara pembayaran sewa rental mobil di Deaz Rental Mobil Banjarmasin.",
};

const rawHtml = `<main class="pt-20"> <!-- Added padding for fixed navbar -->  <main class="mx-auto max-w-screen-xl px-4 my-12"> <!-- Header Section --> <div class="mb-10 text-center"> <h1 class="mb-2 text-3xl font-bold text-gray-800">Metode Pembayaran</h1> <p class="mx-auto max-w-2xl text-gray-600">Berbagai pilihan pembayaran yang mudah dan aman untuk kenyamanan Anda dalam menyewa kendaraan.</p> </div> <div class="flex flex-col gap-8 lg:flex-row"> <!-- Kolom Kiri - Daftar Metode Pembayaran --> <div class="lg:w-1/2"> <h2 class="flex items-center pb-2 mb-6 text-xl font-semibold text-gray-800 border-b border-gray-200"> <i data-lucide="credit-card" class="w-5 h-5 mr-2 text-red-700"></i>
Rekening Bank Resmi
</h2> <div class="space-y-4"> <div class="flex items-center p-4 bg-white rounded-lg border border-gray-100 shadow-sm transition-all hover:border-red-100"> <div class="flex-shrink-0 w-24 mr-4"> <img src="/images/bca_Z2ngJh5.webp" alt="BCA" loading="lazy" decoding="async" fetchpriority="auto" width="100" height="40" class="w-auto h-10 object-contain"> </div> <div> <div class="font-medium text-gray-800">0512274992</div> <div class="text-sm text-gray-500">a.n AZMIANOOR</div> </div> </div> <div class="flex items-center p-4 bg-white rounded-lg border border-gray-100 shadow-sm transition-all hover:border-red-100"> <div class="flex-shrink-0 w-24 mr-4"> <img src="/images/bri_LeIhN.webp" alt="BRI" loading="lazy" decoding="async" fetchpriority="auto" width="100" height="40" class="w-auto h-10 object-contain"> </div> <div> <div class="font-medium text-gray-800">000301001020564</div> <div class="text-sm text-gray-500">a.n AZMIANOOR, SH</div> </div> </div> <div class="flex items-center p-4 bg-white rounded-lg border border-gray-100 shadow-sm transition-all hover:border-red-100"> <div class="flex-shrink-0 w-24 mr-4"> <img src="/images/mandiri_1u4SzS.webp" alt="Mandiri" loading="lazy" decoding="async" fetchpriority="auto" width="100" height="40" class="w-auto h-10 object-contain"> </div> <div> <div class="font-medium text-gray-800">0310015777181</div> <div class="text-sm text-gray-500">a.n AZMIANOOR</div> </div> </div> <div class="flex items-center p-4 bg-white rounded-lg border border-gray-100 shadow-sm transition-all hover:border-red-100"> <div class="flex-shrink-0 w-24 mr-4"> <img src="/images/bni_qViOE.webp" alt="BNI" loading="lazy" decoding="async" fetchpriority="auto" width="100" height="40" class="w-auto h-10 object-contain"> </div> <div> <div class="font-medium text-gray-800">1185485247</div> <div class="text-sm text-gray-500">a.n AZMIANOOR</div> </div> </div> </div> <!-- Proses Pembayaran --> <div class="mt-8"> <h2 class="flex items-center pb-2 mb-6 text-xl font-semibold text-gray-800 border-b border-gray-200"> <i data-lucide="clipboard-list" class="w-5 h-5 mr-2 text-red-700"></i>
Proses Pembayaran
</h2> <ol class="space-y-3 text-gray-700"> <li class="flex items-start"> <div class="flex-shrink-0 w-6 h-6 flex justify-center items-center mr-3 font-semibold text-red-700 bg-red-100 rounded-full">1</div> <span>Pilih kendaraan dan konfirmasi pemesanan</span> </li> <li class="flex items-start"> <div class="flex-shrink-0 w-6 h-6 flex justify-center items-center mr-3 font-semibold text-red-700 bg-red-100 rounded-full">2</div> <span>Transfer ke salah satu rekening bank di atas</span> </li> <li class="flex items-start"> <div class="flex-shrink-0 w-6 h-6 flex justify-center items-center mr-3 font-semibold text-red-700 bg-red-100 rounded-full">3</div> <span>Kirim bukti pembayaran melalui WhatsApp</span> </li> <li class="flex items-start"> <div class="flex-shrink-0 w-6 h-6 flex justify-center items-center mr-3 font-semibold text-red-700 bg-red-100 rounded-full">4</div> <span>Tunggu konfirmasi dari tim kami</span> </li> <li class="flex items-start"> <div class="flex-shrink-0 w-6 h-6 flex justify-center items-center mr-3 font-semibold text-red-700 bg-red-100 rounded-full">5</div> <span>Kendaraan siap digunakan sesuai jadwal</span> </li> </ol> </div> </div> <!-- Kolom Kanan - Informasi Tambahan dan FAQ --> <div class="lg:w-1/2"> <div class="p-6 mb-6 bg-white rounded-lg border border-gray-100 shadow-sm transition-all hover:border-red-100"> <h2 class="flex items-center mb-4 text-xl font-semibold text-red-700"> <i data-lucide="info" class="w-5 h-5 mr-2"></i>
Kebijakan Pembayaran
</h2> <ul class="space-y-3"> <li class="flex items-start"> <i data-lucide="check-circle" class="flex-shrink-0 w-5 h-5 mt-0.5 mr-2 text-red-600"></i> <span class="text-gray-700">Pembayaran harus dilunasi sebelum pengambilan kendaraan</span> </li> <li class="flex items-start"> <i data-lucide="check-circle" class="flex-shrink-0 w-5 h-5 mt-0.5 mr-2 text-red-600"></i> <span class="text-gray-700">Deposit keamanan mungkin diperlukan untuk beberapa jenis kendaraan</span> </li> <li class="flex items-start"> <i data-lucide="check-circle" class="flex-shrink-0 w-5 h-5 mt-0.5 mr-2 text-red-600"></i> <span class="text-gray-700">Pembatalan gratis hingga 24 jam sebelum waktu pengambilan</span> </li> <li class="flex items-start"> <i data-lucide="check-circle" class="flex-shrink-0 w-5 h-5 mt-0.5 mr-2 text-red-600"></i> <span class="text-gray-700">Pengembalian dana akan diproses dalam 3-5 hari kerja</span> </li> <li class="flex items-start"> <i data-lucide="check-circle" class="flex-shrink-0 w-5 h-5 mt-0.5 mr-2 text-red-600"></i> <span class="text-gray-700">Perpanjangan sewa dikenakan biaya sesuai tarif harian</span> </li> </ul> </div> <div class="p-6 bg-white rounded-lg border border-gray-100 shadow-sm transition-all hover:border-red-100"> <h2 class="flex items-center mb-4 text-xl font-semibold text-red-700"> <i data-lucide="help-circle" class="w-5 h-5 mr-2"></i>
FAQ Pembayaran
</h2> <div class="space-y-4"> <div class="p-4 bg-gray-50 rounded-lg border border-gray-100"> <h4 class="flex items-center mb-1 font-medium text-gray-800"> <i data-lucide="help-circle" class="w-4 h-4 mr-2 text-red-600"></i>
Apakah ada biaya tambahan?
</h4> <p class="ml-6 text-gray-600">
Semua biaya sudah termasuk dalam harga sewa, kecuali untuk layanan tambahan yang Anda pilih.
</p> </div> <div class="p-4 bg-gray-50 rounded-lg border border-gray-100"> <h4 class="flex items-center mb-1 font-medium text-gray-800"> <i data-lucide="help-circle" class="w-4 h-4 mr-2 text-red-600"></i>
Bagaimana jika saya ingin memperpanjang masa sewa?
</h4> <p class="ml-6 text-gray-600">
Anda dapat memperpanjang masa sewa dengan menghubungi kami dan melakukan pembayaran tambahan.
</p> </div> <div class="p-4 bg-gray-50 rounded-lg border border-gray-100"> <h4 class="flex items-center mb-1 font-medium text-gray-800"> <i data-lucide="help-circle" class="w-4 h-4 mr-2 text-red-600"></i>
Apakah saya bisa mendapatkan invoice untuk keperluan bisnis?
</h4> <p class="ml-6 text-gray-600">
Ya, kami dapat menyediakan invoice resmi untuk keperluan bisnis Anda.
</p> </div> <div class="p-4 bg-gray-50 rounded-lg border border-gray-100"> <h4 class="flex items-center mb-1 font-medium text-gray-800"> <i data-lucide="help-circle" class="w-4 h-4 mr-2 text-red-600"></i>
Berapa lama proses konfirmasi pembayaran?
</h4> <p class="ml-6 text-gray-600">
Konfirmasi pembayaran biasanya diproses dalam waktu 1-2 jam pada jam kerja.
</p> </div> </div> </div> <!-- Call to Action --> <div class="from-red-700 to-red-800 p-6 mt-6 text-center bg-gradient-to-r rounded-lg shadow-sm"> <h3 class="mb-2 text-xl font-bold text-white">Butuh Bantuan?</h3> <p class="text-opacity-90 mb-4 text-white">Tim kami siap membantu Anda dengan pertanyaan seputar pembayaran</p> <a href="/kontak" class="inline-flex items-center px-5 py-2 text-base font-medium text-red-700 bg-white rounded-md border border-transparent shadow-sm transition-all focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-red-700 hover:bg-gray-100"> <i data-lucide="message-circle" class="w-5 h-5 mr-2"></i>
Hubungi Kami
</a> </div> </div> </div> </main>`;

export default function Page() {
  return <div dangerouslySetInnerHTML={{ __html: rawHtml }} />;
}
