import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Tentang Kami - Deaz Rental Mobil Banjarmasin",
  description: "Profil Deaz Rental Mobil Banjarmasin dan Banjarbaru. Penyedia jasa transportasi sewa mobil terpercaya dengan komitmen pelayanan prima.",
};

const rawHtml = `<main class="pt-20"> <!-- Added padding for fixed navbar -->   <section class="py-10 bg-yellow-500 lg:py-24 sm:py-16"> <div class="mx-auto max-w-7xl px-4 lg:px-8 sm:px-6"> <div class="mx-auto max-w-2xl text-center"> <h1 class="text-3xl font-bold leading-tight text-black lg:text-5xl sm:text-4xl">
Tentang <span class="text-red-800">Deaz</span> Rental Mobil
                    Banjarmasin
</h1> <p class="mt-4 text-lg leading-relaxed text-gray-800">
Deaz Rental adalah penyedia jasa rental mobil terlengkap dan
                    termurah di Banjarmasin dan Banjarbaru.
</p> <p class="mt-4 text-lg leading-relaxed text-gray-800">
Kami berkomitmen untuk memberikan layanan transportasi yang nyaman,
                    aman, dan terjangkau bagi pelanggan kami.
</p> </div> </div> </section>  <section class="py-10 bg-white lg:py-24 sm:py-16"> <div class="mx-auto max-w-5xl px-4 lg:px-8 sm:px-6"> <div class="grid items-center gap-y-10 md:grid-cols-2 md:gap-x-20"> <div class="pr-12 sm:pr-0"> <div class="max-w-xs relative mb-12"> <img src="/images/owner-deaz-rental_Z1iYmhF.webp" alt="owner deaz rental banjarmasin" loading="lazy" decoding="async" fetchpriority="auto" width="400" height="500" class="object-bottom rounded-md shadow-lg"> <img src="/images/15_25gsiR.webp" alt="mobil deaz rental banjarmasin" loading="lazy" decoding="async" fetchpriority="auto" width="400" height="300" class="-bottom-12 -right-12 absolute rounded-md scale-75 origin-bottom-right shadow-lg border-4 border-white"> </div> </div> <div> <h2 class="my-6 text-2xl font-bold leading-tight text-black lg:text-4xl sm:text-3xl">
Siapa Kami
</h2> <p class="mt-4 text-base leading-relaxed text-gray-600"> <strong>Deaz Rental Mobil Banjarmasin</strong> adalah perusahaan rental mobil yang berbasis di
                        Banjarmasin dan Banjarbaru. Kami telah melayani kebutuhan
                        transportasi pelanggan kami dengan berbagai pilihan kendaraan yang
                        sesuai dengan kebutuhan dan anggaran mereka.
</p> <div class="mt-8 grid grid-cols-2 gap-4"> <div class="p-4 bg-gray-50 rounded border text-center"> <span class="block text-3xl font-bold text-red-800">5+</span> <span class="text-sm text-gray-600">Tahun Pengalaman</span> </div> <div class="p-4 bg-gray-50 rounded border text-center"> <span class="block text-3xl font-bold text-red-800">100+</span> <span class="text-sm text-gray-600">Pelanggan Puas</span> </div> </div> </div> </div> </div> </section>  <section class="py-12 bg-gray-50"> <div class="mx-auto max-w-screen-xl px-4"> <div class="p-8 mb-10 text-center"> <h2 class="mb-2 text-3xl font-bold text-gray-900">Layanan Kami</h2> <p class="mx-auto max-w-2xl text-gray-600">Kami menyediakan berbagai pilihan kendaraan berkualitas dengan harga terbaik untuk kebutuhan transportasi Anda</p> </div> <div class="flex flex-col gap-12 lg:flex-row"> <!-- Kolom Kiri - Daftar Kendaraan --> <div class="p-8 bg-white rounded-lg shadow-sm lg:w-1/2"> <div class="flex items-center mb-6"> <span class="mr-3 text-red-700"> <i data-lucide="car" class="w-6 h-6"></i> </span> <h2 class="text-2xl font-bold text-gray-900">Daftar Kendaraan Kami</h2> </div> <p class="mb-6 text-base leading-relaxed text-gray-700">
Kami menyediakan berbagai jenis kendaraan untuk disewa, mulai dari mobil keluarga hingga kendaraan premium:
</p> <div class="grid grid-cols-1 gap-4 md:grid-cols-2"> <!-- Dynamically fetch half the list for two columns logic or just list them all --> <ul class="space-y-3"> <li class="flex items-center text-base"> <span class="mr-2.5 text-red-700"> <i data-lucide="check-circle-2" class="w-5 h-5"></i> </span> Daihatsu Gran Max </li><li class="flex items-center text-base"> <span class="mr-2.5 text-red-700"> <i data-lucide="check-circle-2" class="w-5 h-5"></i> </span> Daihatsu New Xenia </li><li class="flex items-center text-base"> <span class="mr-2.5 text-red-700"> <i data-lucide="check-circle-2" class="w-5 h-5"></i> </span> Isuzu Elf Long </li><li class="flex items-center text-base"> <span class="mr-2.5 text-red-700"> <i data-lucide="check-circle-2" class="w-5 h-5"></i> </span> Mitsubishi Pajero Sport </li><li class="flex items-center text-base"> <span class="mr-2.5 text-red-700"> <i data-lucide="check-circle-2" class="w-5 h-5"></i> </span> Mitsubishi Xpander </li><li class="flex items-center text-base"> <span class="mr-2.5 text-red-700"> <i data-lucide="check-circle-2" class="w-5 h-5"></i> </span> Suzuki Ertiga </li><li class="flex items-center text-base"> <span class="mr-2.5 text-red-700"> <i data-lucide="check-circle-2" class="w-5 h-5"></i> </span> Toyota Alphard </li><li class="flex items-center text-base"> <span class="mr-2.5 text-red-700"> <i data-lucide="check-circle-2" class="w-5 h-5"></i> </span> Toyota Avanza Facelift </li> </ul> <ul class="space-y-3"> <li class="flex items-center text-base"> <span class="mr-2.5 text-red-700"> <i data-lucide="check-circle-2" class="w-5 h-5"></i> </span> Toyota Fortuner GR Sport </li><li class="flex items-center text-base"> <span class="mr-2.5 text-red-700"> <i data-lucide="check-circle-2" class="w-5 h-5"></i> </span> Toyota Hiace Commuter </li><li class="flex items-center text-base"> <span class="mr-2.5 text-red-700"> <i data-lucide="check-circle-2" class="w-5 h-5"></i> </span> Toyota Hiace Premio </li><li class="flex items-center text-base"> <span class="mr-2.5 text-red-700"> <i data-lucide="check-circle-2" class="w-5 h-5"></i> </span> Toyota Innova Reborn V </li><li class="flex items-center text-base"> <span class="mr-2.5 text-red-700"> <i data-lucide="check-circle-2" class="w-5 h-5"></i> </span> Toyota Hilux </li><li class="flex items-center text-base"> <span class="mr-2.5 text-red-700"> <i data-lucide="check-circle-2" class="w-5 h-5"></i> </span> Toyota Innova Zenix </li><li class="flex items-center text-base"> <span class="mr-2.5 text-red-700"> <i data-lucide="check-circle-2" class="w-5 h-5"></i> </span> Toyota New Avanza </li><li class="flex items-center text-base"> <span class="mr-2.5 text-red-700"> <i data-lucide="check-circle-2" class="w-5 h-5"></i> </span> Toyota Veloz Q </li> </ul> </div> <div class="mt-8 text-center"> <a href="/armada" class="inline-flex items-center px-5 py-3 text-base font-medium text-white bg-red-800 rounded-lg transition duration-300 hover:bg-red-700">
Lihat Semua Armada
<i data-lucide="arrow-right" class="w-5 h-5 ml-2"></i> </a> </div> </div> <!-- Kolom Kanan - Informasi Tambahan --> <div class="lg:w-1/2"> <div class="p-8 mb-8 bg-white rounded-lg shadow-sm"> <div class="flex items-center mb-6"> <span class="mr-3 text-red-700"> <i data-lucide="thumbs-up" class="w-6 h-6"></i> </span> <h2 class="text-2xl font-bold text-gray-900">Keunggulan Kami</h2> </div> <ul class="space-y-5 text-left text-gray-700"> <li class="flex items-center p-3 rounded-lg transition duration-300 hover:bg-gray-50"> <div class="flex-shrink-0 w-10 h-10 flex justify-center items-center mr-4 bg-red-100 rounded-full"> <i data-lucide="check" class="w-5 h-5 text-red-700"></i> </div> <span class="font-medium">Harga termurah di Banjarmasin dan Banjarbaru</span> </li><li class="flex items-center p-3 rounded-lg transition duration-300 hover:bg-gray-50"> <div class="flex-shrink-0 w-10 h-10 flex justify-center items-center mr-4 bg-red-100 rounded-full"> <i data-lucide="check" class="w-5 h-5 text-red-700"></i> </div> <span class="font-medium">Armada kendaraan terlengkap</span> </li><li class="flex items-center p-3 rounded-lg transition duration-300 hover:bg-gray-50"> <div class="flex-shrink-0 w-10 h-10 flex justify-center items-center mr-4 bg-red-100 rounded-full"> <i data-lucide="check" class="w-5 h-5 text-red-700"></i> </div> <span class="font-medium">Layanan sewa mobil dengan sopir profesional</span> </li><li class="flex items-center p-3 rounded-lg transition duration-300 hover:bg-gray-50"> <div class="flex-shrink-0 w-10 h-10 flex justify-center items-center mr-4 bg-red-100 rounded-full"> <i data-lucide="check" class="w-5 h-5 text-red-700"></i> </div> <span class="font-medium">Pemesanan mudah melalui website atau kontak langsung</span> </li><li class="flex items-center p-3 rounded-lg transition duration-300 hover:bg-gray-50"> <div class="flex-shrink-0 w-10 h-10 flex justify-center items-center mr-4 bg-red-100 rounded-full"> <i data-lucide="check" class="w-5 h-5 text-red-700"></i> </div> <span class="font-medium">Pelayanan pelanggan yang ramah dan responsif</span> </li> </ul> </div> <div class="from-red-800 to-red-600 p-8 text-white bg-gradient-to-r rounded-lg shadow-sm"> <h3 class="mb-4 text-xl font-bold">Butuh Informasi Lebih Lanjut?</h3> <p class="mb-6">Hubungi kami untuk mendapatkan penawaran terbaik sesuai kebutuhan perjalanan Anda</p> <div class="flex flex-col space-y-3"> <a href="tel:6281255964566" class="inline-flex items-center px-5 py-3 text-base font-medium text-red-800 bg-yellow-400 rounded-lg transition duration-300 hover:bg-yellow-300"> <i data-lucide="phone" class="w-5 h-5 mr-2"></i>
Hubungi Kami
</a> <a href="https://api.whatsapp.com/send/?phone=6281255964566&text=Pak+Saya+Mau+Sewa+Mobil+by+Deazrental.com&type=phone_number&app_absent=0" target="_blank" class="inline-flex items-center px-5 py-3 text-base font-medium text-red-800 bg-yellow-400 rounded-lg transition duration-300 hover:bg-yellow-300"> <i data-lucide="message-circle" class="w-5 h-5 mr-2"></i>
Chat WhatsApp
</a> </div> </div> </div> </div> </div> </section>  </main>`;

export default function Page() {
  return <div dangerouslySetInnerHTML={{ __html: rawHtml }} />;
}
